spring.application.name=springbootmongodb
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.4off614.mongodb.net/intranet-database?retryWrites=true&w=majority&tls=true
spring.data.mongodb.database=intranet-database
server.port=${PORT:8080}
app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200
jwt.secret=b3d9d5a6c4e7f29e1b6c48f1e2a0d396c4a8913f2e0a7c1f9d8b6e3a7f092d71
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=120MB
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true